### PR TITLE
Add rounding functions for `Fixed` (Fixes #153)

### LINKED ISSUE #153: Adding rounding functions for `Fixed`
As I mentioned in #139, there are no rounding functions for `Fixed`.
```julia
julia> round(0.502N0f8)
1.0N0f8

julia> round(0.500Q0f7)
ERROR: MethodError: no method matching round(::Fixed{Int8,7}, ::RoundingMode{:Nearest})
```
An important difference between `Normed` and `Fixed` is that `Normed` has no *tie* (or half) numbers, but `Fixed` has.
So, I also think it is a good idea to support the 2nd argument (i.e. `RoundingMode`) explicitly.

### PR DESCRIPTION
**Pull request by kimikage**
This is a part of #151 and fixes #153.

succeeding PRs: this -> `isinteger`(#120) -> `rem`(#150) -> `Integer`(#154) -> `Rational`(#157)

**Edit:**
~Let's decide #159 first.~ Done.

### CODE REVIEW

**Comment by timholy** [comment]
Let's merge this before #163

**Comment by kimikage** [comment]
Though I merged PR #159, this PR supports `Fixed{Int8,8}` and so on, i.e. I reduced the test cases for `f == 8sizeof(T)` and added TODO comments.
Due to inlining, the `depwarn` is somewhat noisy. (Sorry, I overlooked this.)
In addition, I added support for specifying `RoundingMode` for `round`.

File: src/fixed.jl [hunk 1]
```diff
@@ -91,6 +94,73 @@ end
...
+    f == bitwidth(T) - 1 && return x.i == typemin(T) ? x : zero(x)
+    t = x.i & intmask(x)
+    r = x.i & fracmask(x)
+    _rawone = oneunit(T) << f
+    reinterpret(Fixed{T,f}, (x.i < 0) & (r != 0) ? t + _rawone : t)
+end
+function floor(x::Fixed{T,f}) where {T, f}
+    f == bitwidth(T) && x.i < 0 && throw_converterror(Fixed{T,f}, -1) # TODO: remove this line
+    Fixed{T,f}(x.i & intmask(x), 0)
+end
```
Comment (kimikage) [inline src/fixed.jl]: I would like to confirm just in case, your implementation is much more complex.
https://github.com/JuliaMath/FixedPointNumbers.jl/blob/ebc5efff51c271f2697579625ef47e19d20c39b2/src/fixed.jl#L92-L96
Am I overlooking something?

Comment (timholy) [reply src/fixed.jl]: No, you're absolutely right, the simpler one looks correct. :+1:
