### PR TITLE
Fix Ambiguities

### LINKED ISSUE #101: runtests (in 0.7) fails with  Test.detect_ambiguities(FixedPointNumbers, Base, Core)
i merged manually #100 into master and ran. Precompile works, but Pkg.test fails (obviously with Base.Test and Test as stdlib), but also
```

               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.3420 (2018-01-16 17:34 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit aea9155* (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> using FixedPointNumbers

julia> using Test

julia> Test.detect_ambiguities(FixedPointNumbers, Base, Core)
8-element Array{Tuple{Method,Method},1}:
 ((::Type{Fixed{T,f}})(x) where {T, f} in FixedPointNumbers at /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:8, (::Type{T})(z::Complex) where T<:Real in Base at complex.jl:37)                        
 ((::Type{Normed{T,f}})(x) where {T, f} in FixedPointNumbers at /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:8, (::Type{T})(x::T) where T<:Number in Core at boot.jl:686)                            
 ((::Type{Fixed{T,f}})(x) where {T, f} in FixedPointNumbers at /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:8, (::Type{T})(x::Char) where T<:Number in Core at boot.jl:684)                           
 ((::Type{Normed{T,f}})(x) where {T, f} in FixedPointNumbers at /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:8, (::Type{T})(z::Complex) where T<:Real in Base at complex.jl:37)                      
 ((::Type{Normed{T,f}})(x) where {T, f} in FixedPointNumbers at /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:8, (::Type{T})(x::Base.TwicePrecision) where T<:Number in Base at twiceprecision.jl:243)
 ((::Type{Normed{T,f}})(x) where {T, f} in FixedPointNumbers at /home/lobi/.julia/v0.7/FixedPointNumbers/src/normed.jl:8, (::Type{T})(x::Char) where T<:Number in Core at boot.jl:684)                         
 ((::Type{Fixed{T,f}})(x) where {T, f} in FixedPointNumbers at /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:8, (::Type{T})(x::Base.TwicePrecision) where T<:Number in Base at twiceprecision.jl:243)  
 ((::Type{Fixed{T,f}})(x) where {T, f} in FixedPointNumbers at /home/lobi/.julia/v0.7/FixedPointNumbers/src/fixed.jl:8, (::Type{T})(x::T) where T<:Number in Core at boot.jl:686)                              
```

### PR DESCRIPTION
**Pull request by andreasnoack**
Fixes #101

### CODE REVIEW

File: src/fixed.jl [hunk 1]
```diff
@@ -7,6 +7,9 @@ struct Fixed{T <: Signed,f} <: FixedPoint{T,  f}
     Fixed{T, f}(i::Integer, _) where {T,f} = new{T, f}(i % T)
     Fixed{T, f}(x) where {T,f} = convert(Fixed{T,f}, x)
     Fixed{T, f}(x::Fixed{T,f}) where {T,f} = x
+    Fixed{T, f}(x::Char) where {T,f} = throw(ArgumentError("Fixed cannot be constructed from a Char"))
+    Fixed{T, f}(x::Complex) where {T,f} = Fixed{T, f}(real(x))
```
Comment (timholy) [inline src/fixed.jl]: `real` returns the real part even if there is a non-zero complex part. Would it be better to use `convert` and get the `InexactError`?

Comment (andreasnoack) [reply src/fixed.jl]: Yes, that is a blunder. The reason I ended here is that `Complex{S}`, for some reason, didn't match the ambiguous signature. Guess it will have to be `Fixed{T, f}(convert(real(eltype(x)), x))`. Will push a fix.

**Comment by andreasnoack** [comment]
I think it should be ready now. I've also added some tests.

**Comment by timholy** [comment]
Great, thanks again!
