### PR TITLE
Commonize code between `Fixed` and `Normed`

### LINKED ISSUE #150: Rounding errors in `rem` of `Normed`
As I mentioned in #102, PR #131 did not change the `rem`, so this is a reminder.

> To avoid impact on the performance, this PR does not change the `rem`. 
> https://github.com/JuliaMath/FixedPointNumbers.jl/blob/da3931838dd3a5f03e8ed00542a306d685002e33/src/normed.jl#L67-L70
> 
> Therefore, this does not fix the problems such as:
> ```julia
> julia> using Colors
> 
> julia> white = parse(RGB{Float32}, "white")
> RGB{Float32}(1.0f0,1.0f0,1.0f0)
> 
> julia> convert(RGB{N0f32}, white)
> RGB{N0f32}(0.0,0.0,0.0)
> ```

_Originally posted by @kimikage in https://github.com/JuliaMath/FixedPointNumbers.jl/pull/131#issuecomment-547238807_

```julia
julia> using FixedPointNumbers

julia> for f = 1:32
           F = Normed{UInt32,f}
           rem_one = 1.0f0 % F
           rem_one == one(F) || @show rem_one
       end
rem_one = 1.00000003N7f25
rem_one = 1.00000001N6f26
rem_one = 1.000000007N5f27
rem_one = 1.000000004N4f28
rem_one = 1.000000002N3f29
rem_one = 1.0000000009N2f30
rem_one = 1.0000000005N1f31
rem_one = 0.0N0f32
```

### PR DESCRIPTION
**Pull request by kimikage**
This PR is the first part of #139.
I am very sorry about a conflict with #143, but in the long-term, I think this PR will help enhance the functions (e.g. checked arithmetic).

Because there are many changes, it is recommended that you track changes on a per-commit basis.

This PR includes a minor breaking change, i.e., this change the exception type of `one(Q0f7)` etc. from `InexactError` to `ArgumentError`.

I'm ready to fix `isinteger` (issue #120, PR #123) after the merging this PR. And then, I'll fix the issue #150.

**Edit:**
Rescheduling: this -> **issue #153** -> `isinteger` -> `rem` -> **issue #157**

### CODE REVIEW

File: src/normed.jl [hunk 1]
```diff
@@ -66,55 +68,41 @@ function _convert(::Type{U}, x::Float16) where {T, f, U <: Normed{T,f}}
...
-    significand = xu | (one(xu) << significand_bits)
-    yh = unsafe_trunc(Tw, significand) << (bits - significand_bits)
-    exponent_bias = Tf == Float64 ? 1023 : 127
-    ex = exponent_bias - k + bits - f
+    Tw = f < bitwidth(T) ? T : widen1(T)
+    bits = bitwidth(Tw) - 1
+    xu = reinterpret(Unsigned, x)
+    k = Int(xu >> significand_bits(Tf))
+    k == 0 && return zero(N) # neglect subnormal numbers
+    significand = xu | (one(xu) << significand_bits(Tf))
```
Comment (timholy) [inline src/normed.jl]:
```suggestion
    significand = xu | (oneunit(xu) << significand_bits(Tf))
```
(I failed to notice this earlier.)

**Comment by kimikage** [comment]
> Are the methods removed in 2e19e67 really "useless" without a2e3323? 

https://github.com/JuliaMath/FixedPointNumbers.jl/blob/7ad0f0c460961024191f672332fcf3d7cef655d1/src/FixedPointNumbers.jl#L34-L37

https://github.com/JuliaMath/FixedPointNumbers.jl/blob/7ad0f0c460961024191f672332fcf3d7cef655d1/src/normed.jl#L254-L256

They don't seem to differ in essence.
However, the tests of FixedPointNumbers.jl are somewhat *poor*, so we should to recheck the codes before release.

File: src/normed.jl (hunk 1 above)
Comment (kimikage) [reply src/normed.jl]: Do we need to worry about the difference between `one` and `oneunit` for types without dimensions?
Anyway, I changed `one` to `oneunit` for *future* consistency.

Comment (timholy) [reply src/normed.jl]: Not so far, but in cases where you mean "1 of the given type" then `oneunit` is appropriate, no matter whether it differs from `one`.

`one` is a little weird because it could pretty much be defined as the constant `1`.

**Comment by kimikage** [comment]
I added tests for `reinterpret`, although they have nothing to do with my changes directly.
